### ISSUE TITLE
bad runtime process port

### ISSUE THREAD

**Issue by hsluo** [Khan/frankenserver#3]
Hi,

Just started using frankenserver as it uses fsevents on OSX, but I keep seeing this error every time I open my app in the browser.

```
$ frankenserver/python/dev_appserver.py app.yaml
INFO     2016-04-30 12:07:56,491 sdk_update_checker.py:229] Checking for updates to the SDK.
INFO     2016-04-30 12:07:56,822 api_server.py:205] Starting API server at: http://localhost:64582
INFO     2016-04-30 12:07:56,832 dispatcher.py:198] Starting module "default" running at: http://localhost:8080
INFO     2016-04-30 12:07:56,839 admin_server.py:116] Starting admin server at: http://localhost:8000
ERROR    2016-04-30 12:08:05,802 http_runtime.py:391] bad runtime process port ['127.0.0.1\t64614\n']
ERROR    2016-04-30 12:08:05,805 http_runtime.py:391] bad runtime process port ['127.0.0.1\t64615\n']
ERROR    2016-04-30 12:08:05,806 http_proxy.py:116] bad runtime process port ['127.0.0.1\t64615\n']
INFO     2016-04-30 12:08:05,913 module.py:803] default: "GET / HTTP/1.1" 500 47
ERROR    2016-04-30 12:08:06,032 http_proxy.py:116] bad runtime process port ['127.0.0.1\t64614\n']
INFO     2016-04-30 12:08:06,137 module.py:803] default: "GET /favicon.ico HTTP/1.1" 500 47
```

It seems that `http_runtime.py` failed to find a port, instead it returns host + port. I'm using OSX 10.11.4, Python 2.7.11 from Homebrew, and my app uses the Go runtime. Is there anything I can do about this? Thanks.

**Comment by csilvers** [comment]
I'm afraid we've never done any work in Go, so it's totally possible that our fixes are incomplete for that language.

I'm afraid we can't offer much help here -- but if you figure out what to fix, we're glad to accept patches!

**Comment by hsluo** [comment]
Looked into the upstream code and found that they just check the return value and split it.

```python
# http_runtime.py:328
port = self._process.stdout.readline()
if '\t' in port:  # Split out the host if present.
  host, port = port.split('\t', 1)
```

Maybe we could just do the same?

**Comment by csilvers** [comment]
Sure, makes sense.  Patch welcome!

**Comment by csilvers** [comment]
(Oops, I guess they're pull-requests in github-land.)
