### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by drewwells** [Khan/frankenserver#5]
The last SDK update was 1.9.25 but AppEngine SDK is now 1.9.48.

**Comment by csilvers** [comment]
Wow, time flies.  The project is still active, but we only do the work to update it ourselves when Khan Academy needs to update the SDK, which hasn't been for a while.  We'll do it when we have a chance; it's just a matter of finding time to test the new SDK to make sure it doesn't break anything for us.

**Comment by drewwells** [comment]
Are you having issues with Sierra? I think support for that os upgrade was
added recently.

**Comment by csilvers** [comment]
Good news! -- looking at 1.9.49, it looks like dev_appserver now includes most of the functionality from the frankenserver.  In particular, I see that the file-watcher now respects skip_files.  It also has all the IPv6 patches (with one exception which probably came after they did the mege).

There are a few minor things that frankenserver has that are not in mainline yet, including a resurrection of the fsevents file watcher, and improved pypy support.  But those are minor enough that I don't think there's much reason to recommend the frankenserver over stock appengine sdk anymore.

**Comment by csilvers** [comment]
(but see https://code.google.com/p/googleappengine/issues/detail?id=9300#c36 on how to work around a bug in google's version of this code)
